name: JavaScript
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '*'
jobs:
  # lint:
  #   name: Lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: '16'
  #         cache: 'npm'
  #     - name: Install packages
  #       run: npm ci
  #     - name: Lint typescript
  #       run: npx next lint
  #     - name: Lint stylesheets
  #       run: npm run stylelint
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install packages
        run: npm ci
      - name: Build (verifies types)
        run: npm run build
